import type { SectionRegistryEntry } from './section-types';
import { getComponent } from '../../readme-components';
import { renderAnimations } from '../sections';

export const RAW_SECTION_METADATA: SectionRegistryEntry[] = [
  {
    id: 'header',
    name: 'Header Profile',
    category: 'profile',
    icon: 'Layout',
    description: 'Banners, avatar positioning, located metrics, typing subtitles, and custom status badges.',
    defaultEnabled: true,
    displayOrder: 10,
    renderer: (config, context) => getComponent('Header')?.renderer(config, context) || '',
  },
  {
    id: 'about',
    name: 'About Me',
    category: 'profile',
    icon: 'User',
    description: 'Paragraph introducing yourself, your objectives, and lists of core skills.',
    defaultEnabled: true,
    displayOrder: 20,
    renderer: (config, context) => getComponent('About')?.renderer(config, context) || '',
  },
  {
    id: 'socials',
    name: 'Social Links',
    category: 'profile',
    icon: 'Link',
    description: 'Clickable shields.io contact badges mapping social accounts.',
    defaultEnabled: true,
    displayOrder: 30,
    renderer: (config, context) => getComponent('SocialLinks')?.renderer(config, context) || '',
  },
  {
    id: 'techStack',
    name: 'Tech Stack',
    category: 'profile',
    icon: 'Cpu',
    description: 'Categorized badges illustrating language systems and framework stack proficiencies.',
    defaultEnabled: true,
    displayOrder: 40,
    renderer: (config, context) => getComponent('TechStack')?.renderer(config, context) || '',
  },
  {
    id: 'stats',
    name: 'GitHub Stats',
    category: 'activity',
    icon: 'LineChart',
    description: 'Live-updating statistics, streaks, and top language graphics.',
    defaultEnabled: true,
    displayOrder: 50,
    renderer: (config, context) => getComponent('GitHubStats')?.renderer(config, context) || '',
  },
  {
    id: 'achievements',
    name: 'Achievements & Badges',
    category: 'activity',
    icon: 'Award',
    description: 'GitHub trophies, contribution graph overlays, and activity counters.',
    defaultEnabled: false,
    displayOrder: 60,
    renderer: (config, context) => getComponent('Achievements')?.renderer(config, context) || '',
  },
  {
    id: 'projects',
    name: 'Featured Projects',
    category: 'content',
    icon: 'Folder',
    description: 'Highlighting public repositories using grid cards, tables, or item lists.',
    defaultEnabled: true,
    displayOrder: 70,
    renderer: (config, context) => getComponent('Projects')?.renderer(config, context) || '',
  },
  {
    id: 'support',
    name: 'Support & Sponsorship',
    category: 'content',
    icon: 'Heart',
    description: 'Pledge buttons mapping Buy Me A Coffee and Ko-fi user targets.',
    defaultEnabled: false,
    displayOrder: 80,
    renderer: (config, context) => getComponent('Sponsors')?.renderer(config, context) || '',
  },
  {
    id: 'quotes',
    name: 'Daily Quotes',
    category: 'content',
    icon: 'MessageSquare',
    description: 'Dynamic programming quotes badge.',
    defaultEnabled: false,
    displayOrder: 90,
    renderer: (config, context) => getComponent('Quote')?.renderer(config, context) || '',
  },
  {
    id: 'visitor',
    name: 'Visitor Counter',
    category: 'content',
    icon: 'Eye',
    description: 'Profile views tracking indicator.',
    defaultEnabled: false,
    displayOrder: 100,
    renderer: (config, context) => getComponent('Visitors')?.renderer(config, context) || '',
  },
  {
    id: 'custom',
    name: 'Custom Markdown',
    category: 'content',
    icon: 'FileCode',
    description: 'Custom markdown slot for raw editor overrides.',
    defaultEnabled: false,
    displayOrder: 110,
    renderer: (config) => config?.content || '',
  },
  {
    id: 'animatedComponents',
    name: 'Animated Details',
    category: 'activity',
    icon: 'Sparkles',
    description: 'Typing overlays, waves headers, dots dividers, and footer grids.',
    defaultEnabled: false,
    displayOrder: 120,
    renderer: (config, context) => renderAnimations(config, context?.username),
  }
];

export default RAW_SECTION_METADATA;
